/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/blackWhiteList/': RouteRecordInfo<'/blackWhiteList/', '/blackWhiteList', Record<never, never>, Record<never, never>>,
    '/breadcrumb_setting/': RouteRecordInfo<'/breadcrumb_setting/', '/breadcrumb_setting', Record<never, never>, Record<never, never>>,
    '/data-permission/': RouteRecordInfo<'/data-permission/', '/data-permission', Record<never, never>, Record<never, never>>,
    '/demo/breadcrumb_example/detail1': RouteRecordInfo<'/demo/breadcrumb_example/detail1', '/demo/breadcrumb_example/detail1', Record<never, never>, Record<never, never>>,
    '/demo/breadcrumb_example/detail2': RouteRecordInfo<'/demo/breadcrumb_example/detail2', '/demo/breadcrumb_example/detail2', Record<never, never>, Record<never, never>>,
    '/demo/breadcrumb_example/list1': RouteRecordInfo<'/demo/breadcrumb_example/list1', '/demo/breadcrumb_example/list1', Record<never, never>, Record<never, never>>,
    '/demo/breadcrumb_example/list2': RouteRecordInfo<'/demo/breadcrumb_example/list2', '/demo/breadcrumb_example/list2', Record<never, never>, Record<never, never>>,
    '/demo/multilevel_menu_example/level2/level3/page1': RouteRecordInfo<'/demo/multilevel_menu_example/level2/level3/page1', '/demo/multilevel_menu_example/level2/level3/page1', Record<never, never>, Record<never, never>>,
    '/demo/multilevel_menu_example/level2/level3/page2': RouteRecordInfo<'/demo/multilevel_menu_example/level2/level3/page2', '/demo/multilevel_menu_example/level2/level3/page2', Record<never, never>, Record<never, never>>,
    '/demo/multilevel_menu_example/level2/page': RouteRecordInfo<'/demo/multilevel_menu_example/level2/page', '/demo/multilevel_menu_example/level2/page', Record<never, never>, Record<never, never>>,
    '/demo/multilevel_menu_example/page': RouteRecordInfo<'/demo/multilevel_menu_example/page', '/demo/multilevel_menu_example/page', Record<never, never>, Record<never, never>>,
    '/demo/other_page/': RouteRecordInfo<'/demo/other_page/', '/demo/other_page', Record<never, never>, Record<never, never>>,
    '/demo/other_page/des': RouteRecordInfo<'/demo/other_page/des', '/demo/other_page/des', Record<never, never>, Record<never, never>>,
    '/demo/preview-empty/': RouteRecordInfo<'/demo/preview-empty/', '/demo/preview-empty', Record<never, never>, Record<never, never>>,
    '/demo/single/': RouteRecordInfo<'/demo/single/', '/demo/single', Record<never, never>, Record<never, never>>,
    '/dictionary/': RouteRecordInfo<'/dictionary/', '/dictionary', Record<never, never>, Record<never, never>>,
    '/dictionary/itemlist': RouteRecordInfo<'/dictionary/itemlist', '/dictionary/itemlist', Record<never, never>, Record<never, never>>,
    '/group/': RouteRecordInfo<'/group/', '/group', Record<never, never>, Record<never, never>>,
    '/layout_setting/': RouteRecordInfo<'/layout_setting/', '/layout_setting', Record<never, never>, Record<never, never>>,
    '/log_center/login_history': RouteRecordInfo<'/log_center/login_history', '/log_center/login_history', Record<never, never>, Record<never, never>>,
    '/log_center/operate_history': RouteRecordInfo<'/log_center/operate_history', '/log_center/operate_history', Record<never, never>, Record<never, never>>,
    '/menu_setting/': RouteRecordInfo<'/menu_setting/', '/menu_setting', Record<never, never>, Record<never, never>>,
    '/organization/': RouteRecordInfo<'/organization/', '/organization', Record<never, never>, Record<never, never>>,
    '/other_setting/': RouteRecordInfo<'/other_setting/', '/other_setting', Record<never, never>, Record<never, never>>,
    '/page_animation_setting/': RouteRecordInfo<'/page_animation_setting/', '/page_animation_setting', Record<never, never>, Record<never, never>>,
    '/page_w_setting/': RouteRecordInfo<'/page_w_setting/', '/page_w_setting', Record<never, never>, Record<never, never>>,
    'personalNotification': RouteRecordInfo<'personalNotification', '/personal/notification', Record<never, never>, Record<never, never>>,
    '/position/': RouteRecordInfo<'/position/', '/position', Record<never, never>, Record<never, never>>,
    '/region/': RouteRecordInfo<'/region/', '/region', Record<never, never>, Record<never, never>>,
    '/resource/': RouteRecordInfo<'/resource/', '/resource', Record<never, never>, Record<never, never>>,
    '/role/': RouteRecordInfo<'/role/', '/role', Record<never, never>, Record<never, never>>,
    '/safe_setting/': RouteRecordInfo<'/safe_setting/', '/safe_setting', Record<never, never>, Record<never, never>>,
    'home': RouteRecordInfo<'home', '/system', Record<never, never>, Record<never, never>>,
    'notFound': RouteRecordInfo<'notFound', '/system/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/system/auth': RouteRecordInfo<'/system/auth', '/system/auth', Record<never, never>, Record<never, never>>,
    '/system/change-organization/': RouteRecordInfo<'/system/change-organization/', '/system/change-organization', Record<never, never>, Record<never, never>>,
    '/system/change-password/': RouteRecordInfo<'/system/change-password/', '/system/change-password', Record<never, never>, Record<never, never>>,
    '/system/change-password/page': RouteRecordInfo<'/system/change-password/page', '/system/change-password/page', Record<never, never>, Record<never, never>>,
    '/system/login/login': RouteRecordInfo<'/system/login/login', '/system/login/login', Record<never, never>, Record<never, never>>,
    '/system/notPermission/': RouteRecordInfo<'/system/notPermission/', '/system/notPermission', Record<never, never>, Record<never, never>>,
    'reload': RouteRecordInfo<'reload', '/system/reload', Record<never, never>, Record<never, never>>,
    '/tabbar_setting/': RouteRecordInfo<'/tabbar_setting/', '/tabbar_setting', Record<never, never>, Record<never, never>>,
    '/tenant/': RouteRecordInfo<'/tenant/', '/tenant', Record<never, never>, Record<never, never>>,
    '/theme_setting/': RouteRecordInfo<'/theme_setting/', '/theme_setting', Record<never, never>, Record<never, never>>,
    '/toolbar_setting/': RouteRecordInfo<'/toolbar_setting/', '/toolbar_setting', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
    '/watermark_setting/': RouteRecordInfo<'/watermark_setting/', '/watermark_setting', Record<never, never>, Record<never, never>>,
  }
}
